-- ============================================================================
-- LLM Translation Schema Extension
-- ============================================================================
-- This schema extends the medical_terms system to support automatic Japanese
-- label generation using multiple LLM models from HuggingFace.
--
-- Features:
-- - Store translations from multiple LLM models
-- - Track which model generated which translation
-- - Support voting/selection mechanism
-- - Track confidence scores
-- - Record which external IDs were used as context
-- ============================================================================

-- ============================================================================
-- LLM TRANSLATIONS TABLE - Store all LLM-generated translations
-- ============================================================================

CREATE TABLE IF NOT EXISTS llm_translations (
    id BIGSERIAL PRIMARY KEY,

    -- Link to medical term
    qid TEXT NOT NULL,
    CONSTRAINT fk_medical_term
        FOREIGN KEY(qid)
        REFERENCES medical_terms(qid)
        ON DELETE CASCADE,

    -- LLM model information
    model_name TEXT NOT NULL,           -- e.g., "meta-llama/Meta-Llama-3-8B-Instruct"
    model_provider TEXT DEFAULT 'huggingface',  -- huggingface, openai, anthropic, etc.

    -- Generated translation
    suggested_ja_label TEXT NOT NULL,

    -- Context and metadata
    source_fields_used JSONB,           -- Which fields were used (mesh_id, icd10, etc.)
    prompt_template TEXT,               -- The prompt template used
    prompt_filled TEXT,                 -- The actual prompt sent to LLM

    -- Quality metrics
    confidence_score FLOAT,             -- Model's confidence (0.0-1.0) if available
    generation_time_ms INTEGER,         -- Time taken to generate (milliseconds)

    -- Status
    status TEXT DEFAULT 'pending',      -- pending, approved, rejected, selected

    -- Voting/selection
    human_verified BOOLEAN DEFAULT FALSE,
    human_feedback TEXT,                -- Optional feedback from human reviewer

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Ensure unique combination of qid and model
    CONSTRAINT unique_qid_model UNIQUE (qid, model_name)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_llm_translations_qid
    ON llm_translations(qid);

CREATE INDEX IF NOT EXISTS idx_llm_translations_model
    ON llm_translations(model_name);

CREATE INDEX IF NOT EXISTS idx_llm_translations_status
    ON llm_translations(status);

CREATE INDEX IF NOT EXISTS idx_llm_translations_created_at
    ON llm_translations(created_at DESC);

COMMENT ON TABLE llm_translations IS 'Store Japanese label translations generated by various LLM models';

-- ============================================================================
-- EXTEND MEDICAL_TERMS TABLE - Add LLM translation metadata
-- ============================================================================

-- Add columns to track LLM-generated labels
ALTER TABLE medical_terms
ADD COLUMN IF NOT EXISTS ja_label_source TEXT,              -- 'manual', 'wikidata', 'llm', 'hybrid'
ADD COLUMN IF NOT EXISTS ja_label_selected_from TEXT,       -- Model name if from LLM
ADD COLUMN IF NOT EXISTS ja_label_auto_generated BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ja_label_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ja_label_verification_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS ja_label_notes TEXT;               -- Additional notes

COMMENT ON COLUMN medical_terms.ja_label_source IS 'Source of Japanese label: manual, wikidata, llm, or hybrid';
COMMENT ON COLUMN medical_terms.ja_label_selected_from IS 'LLM model name if label was auto-generated';
COMMENT ON COLUMN medical_terms.ja_label_auto_generated IS 'Whether the label was automatically generated by LLM';
COMMENT ON COLUMN medical_terms.ja_label_verified IS 'Whether a human has verified the auto-generated label';

-- ============================================================================
-- TRANSLATION JOBS TABLE - Track batch translation jobs
-- ============================================================================

CREATE TABLE IF NOT EXISTS translation_jobs (
    id BIGSERIAL PRIMARY KEY,

    -- Job metadata
    status TEXT NOT NULL DEFAULT 'pending',  -- pending, running, completed, failed
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,

    -- Job configuration
    models_used TEXT[],                 -- Array of model names
    filter_criteria JSONB,              -- Criteria for selecting terms to translate

    -- Statistics
    total_terms INTEGER DEFAULT 0,
    terms_processed INTEGER DEFAULT 0,
    terms_failed INTEGER DEFAULT 0,

    -- Results
    translations_generated INTEGER DEFAULT 0,
    average_generation_time_ms FLOAT,

    -- Execution environment
    execution_environment TEXT,         -- github_actions, local, manual
    github_run_id TEXT,
    github_actor TEXT,

    -- Error tracking
    error_message TEXT,
    error_details JSONB,

    -- Additional metadata
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_translation_jobs_status
    ON translation_jobs(status);

CREATE INDEX IF NOT EXISTS idx_translation_jobs_started_at
    ON translation_jobs(started_at DESC);

COMMENT ON TABLE translation_jobs IS 'Track batch translation jobs using LLMs';

-- ============================================================================
-- HELPER VIEWS
-- ============================================================================

-- View: Terms needing Japanese translation
CREATE OR REPLACE VIEW terms_needing_ja_translation AS
SELECT
    qid,
    en_label,
    en_description,
    category_en,
    mesh_id,
    icd10,
    icd11,
    icd9,
    snomed_id,
    umls_id,
    created_at,
    updated_at
FROM medical_terms
WHERE (ja_label IS NULL OR ja_label = '')
  AND en_label IS NOT NULL
  AND en_label != ''
ORDER BY updated_at DESC;

COMMENT ON VIEW terms_needing_ja_translation IS 'Medical terms that have English labels but no Japanese labels';

-- View: LLM translation candidates with external IDs
CREATE OR REPLACE VIEW translation_candidates_with_context AS
SELECT
    qid,
    en_label,
    en_description,
    category_en,
    -- Count available external IDs (more IDs = better context)
    (CASE WHEN mesh_id IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN icd10 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN icd11 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN snomed_id IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN umls_id IS NOT NULL THEN 1 ELSE 0 END) as external_id_count,
    mesh_id,
    icd10,
    icd11,
    snomed_id,
    umls_id,
    -- Check if already has LLM translations
    (SELECT COUNT(*) FROM llm_translations lt WHERE lt.qid = mt.qid) as existing_translations
FROM medical_terms mt
WHERE (ja_label IS NULL OR ja_label = '')
  AND en_label IS NOT NULL
  AND en_label != ''
ORDER BY external_id_count DESC, updated_at DESC;

COMMENT ON VIEW translation_candidates_with_context IS 'Translation candidates ranked by available context (external IDs)';

-- View: Translation consensus
CREATE OR REPLACE VIEW translation_consensus AS
SELECT
    qid,
    suggested_ja_label,
    COUNT(*) as model_count,
    ARRAY_AGG(model_name ORDER BY model_name) as agreeing_models,
    AVG(confidence_score) as avg_confidence,
    MIN(created_at) as first_suggested_at,
    MAX(created_at) as last_suggested_at
FROM llm_translations
WHERE status != 'rejected'
GROUP BY qid, suggested_ja_label
HAVING COUNT(*) > 1  -- Only show translations suggested by multiple models
ORDER BY model_count DESC, avg_confidence DESC;

COMMENT ON VIEW translation_consensus IS 'Japanese translations suggested by multiple LLM models (consensus)';

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Function: Get best translation by voting
CREATE OR REPLACE FUNCTION get_best_translation(term_qid TEXT)
RETURNS TABLE (
    suggested_ja_label TEXT,
    vote_count BIGINT,
    avg_confidence FLOAT,
    models TEXT[]
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        lt.suggested_ja_label,
        COUNT(*) as vote_count,
        AVG(lt.confidence_score) as avg_confidence,
        ARRAY_AGG(lt.model_name ORDER BY lt.model_name) as models
    FROM llm_translations lt
    WHERE lt.qid = term_qid
      AND lt.status != 'rejected'
    GROUP BY lt.suggested_ja_label
    ORDER BY COUNT(*) DESC, AVG(lt.confidence_score) DESC
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION get_best_translation IS 'Get the best Japanese translation based on voting and confidence';

-- Function: Apply best translation to medical_terms
CREATE OR REPLACE FUNCTION apply_best_translation(term_qid TEXT)
RETURNS VOID AS $$
DECLARE
    best_translation TEXT;
    top_model TEXT;
BEGIN
    -- Get the most voted translation
    SELECT suggested_ja_label, model_name
    INTO best_translation, top_model
    FROM llm_translations
    WHERE qid = term_qid
      AND status != 'rejected'
    GROUP BY suggested_ja_label, model_name
    ORDER BY COUNT(*) DESC, confidence_score DESC
    LIMIT 1;

    -- Update medical_terms if translation found
    IF best_translation IS NOT NULL THEN
        UPDATE medical_terms
        SET
            ja_label = best_translation,
            ja_label_source = 'llm',
            ja_label_selected_from = top_model,
            ja_label_auto_generated = TRUE,
            ja_label_verified = FALSE,
            updated_at = NOW()
        WHERE qid = term_qid;

        -- Mark the selected translation
        UPDATE llm_translations
        SET status = 'selected'
        WHERE qid = term_qid
          AND suggested_ja_label = best_translation;
    END IF;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION apply_best_translation IS 'Apply the best voted LLM translation to the medical_terms table';

-- ============================================================================
-- USEFUL QUERIES
-- ============================================================================

-- Count terms needing translation
-- SELECT COUNT(*) FROM terms_needing_ja_translation;

-- Get top candidates with most context
-- SELECT * FROM translation_candidates_with_context LIMIT 20;

-- View translations for a specific term
-- SELECT * FROM llm_translations WHERE qid = 'Q12136' ORDER BY created_at;

-- Get consensus translations
-- SELECT * FROM translation_consensus LIMIT 20;

-- Get best translation for a term
-- SELECT * FROM get_best_translation('Q12136');

-- Apply best translations to all terms
-- SELECT apply_best_translation(qid) FROM terms_needing_ja_translation;

-- Count translations by model
-- SELECT model_name, COUNT(*) as translation_count
-- FROM llm_translations
-- GROUP BY model_name
-- ORDER BY translation_count DESC;

-- View translation job history
-- SELECT * FROM translation_jobs ORDER BY started_at DESC;
